// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/out.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OutMap struct {
	Source     string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Width      int64  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height     int64  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	TileWidth  int64  `protobuf:"varint,5,opt,name=tile_width,json=tileWidth,proto3" json:"tile_width,omitempty"`
	TileHeight int64  `protobuf:"varint,6,opt,name=tile_height,json=tileHeight,proto3" json:"tile_height,omitempty"`
	TileCount  int64  `protobuf:"varint,7,opt,name=tile_count,json=tileCount,proto3" json:"tile_count,omitempty"`
	// repeated Property properties = 7;
	Layers               []*OutLayer `protobuf:"bytes,8,rep,name=layers,proto3" json:"layers,omitempty"`
	Colliders            []*Collider `protobuf:"bytes,9,rep,name=colliders,proto3" json:"colliders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OutMap) Reset()         { *m = OutMap{} }
func (m *OutMap) String() string { return proto.CompactTextString(m) }
func (*OutMap) ProtoMessage()    {}
func (*OutMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_705866a120287d7e, []int{0}
}

func (m *OutMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutMap.Unmarshal(m, b)
}
func (m *OutMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutMap.Marshal(b, m, deterministic)
}
func (m *OutMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutMap.Merge(m, src)
}
func (m *OutMap) XXX_Size() int {
	return xxx_messageInfo_OutMap.Size(m)
}
func (m *OutMap) XXX_DiscardUnknown() {
	xxx_messageInfo_OutMap.DiscardUnknown(m)
}

var xxx_messageInfo_OutMap proto.InternalMessageInfo

func (m *OutMap) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *OutMap) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *OutMap) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *OutMap) GetTileWidth() int64 {
	if m != nil {
		return m.TileWidth
	}
	return 0
}

func (m *OutMap) GetTileHeight() int64 {
	if m != nil {
		return m.TileHeight
	}
	return 0
}

func (m *OutMap) GetTileCount() int64 {
	if m != nil {
		return m.TileCount
	}
	return 0
}

func (m *OutMap) GetLayers() []*OutLayer {
	if m != nil {
		return m.Layers
	}
	return nil
}

func (m *OutMap) GetColliders() []*Collider {
	if m != nil {
		return m.Colliders
	}
	return nil
}

type OutLayer struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Opacity              float32    `protobuf:"fixed32,2,opt,name=opacity,proto3" json:"opacity,omitempty"`
	Tiles                []*OutTile `protobuf:"bytes,4,rep,name=tiles,proto3" json:"tiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OutLayer) Reset()         { *m = OutLayer{} }
func (m *OutLayer) String() string { return proto.CompactTextString(m) }
func (*OutLayer) ProtoMessage()    {}
func (*OutLayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_705866a120287d7e, []int{1}
}

func (m *OutLayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutLayer.Unmarshal(m, b)
}
func (m *OutLayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutLayer.Marshal(b, m, deterministic)
}
func (m *OutLayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutLayer.Merge(m, src)
}
func (m *OutLayer) XXX_Size() int {
	return xxx_messageInfo_OutLayer.Size(m)
}
func (m *OutLayer) XXX_DiscardUnknown() {
	xxx_messageInfo_OutLayer.DiscardUnknown(m)
}

var xxx_messageInfo_OutLayer proto.InternalMessageInfo

func (m *OutLayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OutLayer) GetOpacity() float32 {
	if m != nil {
		return m.Opacity
	}
	return 0
}

func (m *OutLayer) GetTiles() []*OutTile {
	if m != nil {
		return m.Tiles
	}
	return nil
}

type OutTile struct {
	Gid                  uint32   `protobuf:"fixed32,1,opt,name=gid,proto3" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutTile) Reset()         { *m = OutTile{} }
func (m *OutTile) String() string { return proto.CompactTextString(m) }
func (*OutTile) ProtoMessage()    {}
func (*OutTile) Descriptor() ([]byte, []int) {
	return fileDescriptor_705866a120287d7e, []int{2}
}

func (m *OutTile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutTile.Unmarshal(m, b)
}
func (m *OutTile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutTile.Marshal(b, m, deterministic)
}
func (m *OutTile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutTile.Merge(m, src)
}
func (m *OutTile) XXX_Size() int {
	return xxx_messageInfo_OutTile.Size(m)
}
func (m *OutTile) XXX_DiscardUnknown() {
	xxx_messageInfo_OutTile.DiscardUnknown(m)
}

var xxx_messageInfo_OutTile proto.InternalMessageInfo

func (m *OutTile) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

type Collider struct {
	IsCollider           bool     `protobuf:"varint,1,opt,name=is_collider,json=isCollider,proto3" json:"is_collider,omitempty"`
	Cost                 float32  `protobuf:"fixed32,2,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collider) Reset()         { *m = Collider{} }
func (m *Collider) String() string { return proto.CompactTextString(m) }
func (*Collider) ProtoMessage()    {}
func (*Collider) Descriptor() ([]byte, []int) {
	return fileDescriptor_705866a120287d7e, []int{3}
}

func (m *Collider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collider.Unmarshal(m, b)
}
func (m *Collider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collider.Marshal(b, m, deterministic)
}
func (m *Collider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collider.Merge(m, src)
}
func (m *Collider) XXX_Size() int {
	return xxx_messageInfo_Collider.Size(m)
}
func (m *Collider) XXX_DiscardUnknown() {
	xxx_messageInfo_Collider.DiscardUnknown(m)
}

var xxx_messageInfo_Collider proto.InternalMessageInfo

func (m *Collider) GetIsCollider() bool {
	if m != nil {
		return m.IsCollider
	}
	return false
}

func (m *Collider) GetCost() float32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func init() {
	proto.RegisterType((*OutMap)(nil), "pb.OutMap")
	proto.RegisterType((*OutLayer)(nil), "pb.OutLayer")
	proto.RegisterType((*OutTile)(nil), "pb.OutTile")
	proto.RegisterType((*Collider)(nil), "pb.Collider")
}

func init() { proto.RegisterFile("pb/out.proto", fileDescriptor_705866a120287d7e) }

var fileDescriptor_705866a120287d7e = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4d, 0x4b, 0xf3, 0x40,
	0x14, 0x85, 0x49, 0x93, 0xe6, 0xe3, 0xb6, 0x8b, 0x97, 0xcb, 0x8b, 0x0c, 0x88, 0x58, 0x83, 0x8b,
	0xe2, 0x22, 0x82, 0xfe, 0x00, 0x17, 0xdd, 0xb8, 0x50, 0x0a, 0x83, 0xe0, 0xc2, 0x45, 0xc9, 0xc7,
	0xd0, 0x0c, 0xc4, 0xce, 0x90, 0x99, 0x20, 0xfd, 0xf5, 0xca, 0xdc, 0x4c, 0x0c, 0xee, 0xee, 0x3d,
	0xe7, 0x3c, 0xc9, 0xe1, 0x0e, 0xac, 0x75, 0x75, 0xaf, 0x06, 0x5b, 0xe8, 0x5e, 0x59, 0x85, 0x0b,
	0x5d, 0xe5, 0xdf, 0x01, 0xc4, 0xfb, 0xc1, 0xbe, 0x96, 0x1a, 0x2f, 0x20, 0x36, 0x6a, 0xe8, 0x6b,
	0xc1, 0x16, 0x9b, 0x60, 0x9b, 0x71, 0xbf, 0xe1, 0x7f, 0x58, 0x7e, 0xc9, 0xc6, 0xb6, 0x2c, 0xdc,
	0x04, 0xdb, 0x90, 0x8f, 0x8b, 0x4b, 0xb7, 0x42, 0x1e, 0x5b, 0xcb, 0x22, 0x92, 0xfd, 0x86, 0x57,
	0x00, 0x56, 0x76, 0xe2, 0x30, 0x22, 0x4b, 0xf2, 0x32, 0xa7, 0xbc, 0x13, 0x76, 0x0d, 0x2b, 0xb2,
	0x3d, 0x1b, 0x93, 0x4f, 0xc4, 0xf3, 0x5f, 0xbe, 0x56, 0xc3, 0xc9, 0xb2, 0x64, 0xe6, 0x77, 0x4e,
	0xc0, 0x5b, 0x88, 0xbb, 0xf2, 0x2c, 0x7a, 0xc3, 0xd2, 0x4d, 0xb8, 0x5d, 0x3d, 0xac, 0x0b, 0x5d,
	0x15, 0xfb, 0xc1, 0xbe, 0x38, 0x91, 0x7b, 0x0f, 0xef, 0x20, 0xab, 0x55, 0xd7, 0xc9, 0xc6, 0x05,
	0xb3, 0x39, 0xb8, 0xf3, 0x22, 0x9f, 0xed, 0xfc, 0x03, 0xd2, 0x89, 0x47, 0x84, 0xe8, 0x54, 0x7e,
	0x0a, 0x16, 0xd0, 0x01, 0x68, 0x46, 0x06, 0x89, 0xd2, 0x65, 0x2d, 0xed, 0x99, 0xee, 0xb2, 0xe0,
	0xd3, 0x8a, 0x37, 0xb0, 0x74, 0xc5, 0x0c, 0x8b, 0xe8, 0x0f, 0x2b, 0x5f, 0xe5, 0x4d, 0x76, 0x82,
	0x8f, 0x4e, 0x7e, 0x09, 0x89, 0x57, 0xf0, 0x1f, 0x84, 0x47, 0xd9, 0xd0, 0xa7, 0x13, 0xee, 0xc6,
	0xfc, 0x09, 0xd2, 0xa9, 0x90, 0xbb, 0x8b, 0x34, 0x87, 0xa9, 0x15, 0xa5, 0x52, 0x0e, 0xd2, 0xfc,
	0x06, 0x10, 0xa2, 0x5a, 0x19, 0xeb, 0x3b, 0xd0, 0x5c, 0xc5, 0xf4, 0x8e, 0x8f, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xd2, 0xd9, 0xca, 0x13, 0xd7, 0x01, 0x00, 0x00,
}
