// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/tmx.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Map struct {
	Version              string         `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Orientation          string         `protobuf:"bytes,2,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Width                int64          `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int64          `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	TileWidth            int64          `protobuf:"varint,5,opt,name=tile_width,json=tileWidth,proto3" json:"tile_width,omitempty"`
	TileHeight           int64          `protobuf:"varint,6,opt,name=tile_height,json=tileHeight,proto3" json:"tile_height,omitempty"`
	Properties           []*Property    `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty"`
	Layers               []*Layer       `protobuf:"bytes,8,rep,name=layers,proto3" json:"layers,omitempty"`
	ObjectGroups         []*ObjectGroup `protobuf:"bytes,9,rep,name=object_groups,json=objectGroups,proto3" json:"object_groups,omitempty"`
	TiledVersion         string         `protobuf:"bytes,10,opt,name=tiled_version,json=tiledVersion,proto3" json:"tiled_version,omitempty"`
	RenderOrder          string         `protobuf:"bytes,11,opt,name=render_order,json=renderOrder,proto3" json:"render_order,omitempty"`
	Infinite             int64          `protobuf:"varint,12,opt,name=infinite,proto3" json:"infinite,omitempty"`
	HexSideLength        int64          `protobuf:"varint,13,opt,name=hex_side_length,json=hexSideLength,proto3" json:"hex_side_length,omitempty"`
	StaggerAxis          string         `protobuf:"bytes,14,opt,name=stagger_axis,json=staggerAxis,proto3" json:"stagger_axis,omitempty"`
	BackgroundColor      string         `protobuf:"bytes,15,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"`
	NextLayerId          string         `protobuf:"bytes,16,opt,name=next_layer_id,json=nextLayerId,proto3" json:"next_layer_id,omitempty"`
	NextObjectId         string         `protobuf:"bytes,17,opt,name=next_object_id,json=nextObjectId,proto3" json:"next_object_id,omitempty"`
	TileSets             []*TileSet     `protobuf:"bytes,18,rep,name=tile_sets,json=tileSets,proto3" json:"tile_sets,omitempty"`
	ImageLayers          []*ImageLayer  `protobuf:"bytes,19,rep,name=image_layers,json=imageLayers,proto3" json:"image_layers,omitempty"`
	Groups               []*Group       `protobuf:"bytes,20,rep,name=groups,proto3" json:"groups,omitempty"`
	Colliders            []*Collider    `protobuf:"bytes,21,rep,name=colliders,proto3" json:"colliders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Map) Reset()         { *m = Map{} }
func (m *Map) String() string { return proto.CompactTextString(m) }
func (*Map) ProtoMessage()    {}
func (*Map) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{0}
}

func (m *Map) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Map.Unmarshal(m, b)
}
func (m *Map) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Map.Marshal(b, m, deterministic)
}
func (m *Map) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Map.Merge(m, src)
}
func (m *Map) XXX_Size() int {
	return xxx_messageInfo_Map.Size(m)
}
func (m *Map) XXX_DiscardUnknown() {
	xxx_messageInfo_Map.DiscardUnknown(m)
}

var xxx_messageInfo_Map proto.InternalMessageInfo

func (m *Map) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Map) GetOrientation() string {
	if m != nil {
		return m.Orientation
	}
	return ""
}

func (m *Map) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Map) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Map) GetTileWidth() int64 {
	if m != nil {
		return m.TileWidth
	}
	return 0
}

func (m *Map) GetTileHeight() int64 {
	if m != nil {
		return m.TileHeight
	}
	return 0
}

func (m *Map) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Map) GetLayers() []*Layer {
	if m != nil {
		return m.Layers
	}
	return nil
}

func (m *Map) GetObjectGroups() []*ObjectGroup {
	if m != nil {
		return m.ObjectGroups
	}
	return nil
}

func (m *Map) GetTiledVersion() string {
	if m != nil {
		return m.TiledVersion
	}
	return ""
}

func (m *Map) GetRenderOrder() string {
	if m != nil {
		return m.RenderOrder
	}
	return ""
}

func (m *Map) GetInfinite() int64 {
	if m != nil {
		return m.Infinite
	}
	return 0
}

func (m *Map) GetHexSideLength() int64 {
	if m != nil {
		return m.HexSideLength
	}
	return 0
}

func (m *Map) GetStaggerAxis() string {
	if m != nil {
		return m.StaggerAxis
	}
	return ""
}

func (m *Map) GetBackgroundColor() string {
	if m != nil {
		return m.BackgroundColor
	}
	return ""
}

func (m *Map) GetNextLayerId() string {
	if m != nil {
		return m.NextLayerId
	}
	return ""
}

func (m *Map) GetNextObjectId() string {
	if m != nil {
		return m.NextObjectId
	}
	return ""
}

func (m *Map) GetTileSets() []*TileSet {
	if m != nil {
		return m.TileSets
	}
	return nil
}

func (m *Map) GetImageLayers() []*ImageLayer {
	if m != nil {
		return m.ImageLayers
	}
	return nil
}

func (m *Map) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *Map) GetColliders() []*Collider {
	if m != nil {
		return m.Colliders
	}
	return nil
}

type Tile struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Terrain              string   `protobuf:"bytes,3,opt,name=terrain,proto3" json:"terrain,omitempty"`
	Probability          float32  `protobuf:"fixed32,4,opt,name=probability,proto3" json:"probability,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tile) Reset()         { *m = Tile{} }
func (m *Tile) String() string { return proto.CompactTextString(m) }
func (*Tile) ProtoMessage()    {}
func (*Tile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{1}
}

func (m *Tile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tile.Unmarshal(m, b)
}
func (m *Tile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tile.Marshal(b, m, deterministic)
}
func (m *Tile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tile.Merge(m, src)
}
func (m *Tile) XXX_Size() int {
	return xxx_messageInfo_Tile.Size(m)
}
func (m *Tile) XXX_DiscardUnknown() {
	xxx_messageInfo_Tile.DiscardUnknown(m)
}

var xxx_messageInfo_Tile proto.InternalMessageInfo

func (m *Tile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Tile) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Tile) GetTerrain() string {
	if m != nil {
		return m.Terrain
	}
	return ""
}

func (m *Tile) GetProbability() float32 {
	if m != nil {
		return m.Probability
	}
	return 0
}

type TileSet struct {
	FirstGid             int64       `protobuf:"varint,1,opt,name=first_gid,json=firstGid,proto3" json:"first_gid,omitempty"`
	Source               string      `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	TileWidth            int64       `protobuf:"varint,4,opt,name=tile_width,json=tileWidth,proto3" json:"tile_width,omitempty"`
	TileHeight           int64       `protobuf:"varint,5,opt,name=tile_height,json=tileHeight,proto3" json:"tile_height,omitempty"`
	Spacing              int64       `protobuf:"varint,6,opt,name=spacing,proto3" json:"spacing,omitempty"`
	Margin               int64       `protobuf:"varint,7,opt,name=margin,proto3" json:"margin,omitempty"`
	Properties           []*Property `protobuf:"bytes,8,rep,name=properties,proto3" json:"properties,omitempty"`
	Image                *Image      `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	Tiles                []*Tile     `protobuf:"bytes,10,rep,name=tiles,proto3" json:"tiles,omitempty"`
	TileCount            int64       `protobuf:"varint,11,opt,name=tile_count,json=tileCount,proto3" json:"tile_count,omitempty"`
	ColumnCount          int64       `protobuf:"varint,12,opt,name=column_count,json=columnCount,proto3" json:"column_count,omitempty"`
	Version              string      `protobuf:"bytes,13,opt,name=version,proto3" json:"version,omitempty"`
	TiledVersion         string      `protobuf:"bytes,14,opt,name=tiled_version,json=tiledVersion,proto3" json:"tiled_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TileSet) Reset()         { *m = TileSet{} }
func (m *TileSet) String() string { return proto.CompactTextString(m) }
func (*TileSet) ProtoMessage()    {}
func (*TileSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{2}
}

func (m *TileSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TileSet.Unmarshal(m, b)
}
func (m *TileSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TileSet.Marshal(b, m, deterministic)
}
func (m *TileSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TileSet.Merge(m, src)
}
func (m *TileSet) XXX_Size() int {
	return xxx_messageInfo_TileSet.Size(m)
}
func (m *TileSet) XXX_DiscardUnknown() {
	xxx_messageInfo_TileSet.DiscardUnknown(m)
}

var xxx_messageInfo_TileSet proto.InternalMessageInfo

func (m *TileSet) GetFirstGid() int64 {
	if m != nil {
		return m.FirstGid
	}
	return 0
}

func (m *TileSet) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TileSet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TileSet) GetTileWidth() int64 {
	if m != nil {
		return m.TileWidth
	}
	return 0
}

func (m *TileSet) GetTileHeight() int64 {
	if m != nil {
		return m.TileHeight
	}
	return 0
}

func (m *TileSet) GetSpacing() int64 {
	if m != nil {
		return m.Spacing
	}
	return 0
}

func (m *TileSet) GetMargin() int64 {
	if m != nil {
		return m.Margin
	}
	return 0
}

func (m *TileSet) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *TileSet) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *TileSet) GetTiles() []*Tile {
	if m != nil {
		return m.Tiles
	}
	return nil
}

func (m *TileSet) GetTileCount() int64 {
	if m != nil {
		return m.TileCount
	}
	return 0
}

func (m *TileSet) GetColumnCount() int64 {
	if m != nil {
		return m.ColumnCount
	}
	return 0
}

func (m *TileSet) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *TileSet) GetTiledVersion() string {
	if m != nil {
		return m.TiledVersion
	}
	return ""
}

type Data struct {
	Encoding             string      `protobuf:"bytes,1,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Compression          string      `protobuf:"bytes,2,opt,name=compression,proto3" json:"compression,omitempty"`
	RawData              string      `protobuf:"bytes,3,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	DataTiles            []*DataTile `protobuf:"bytes,4,rep,name=data_tiles,json=dataTiles,proto3" json:"data_tiles,omitempty"`
	Chunks               []*Chunk    `protobuf:"bytes,5,rep,name=chunks,proto3" json:"chunks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{3}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *Data) GetCompression() string {
	if m != nil {
		return m.Compression
	}
	return ""
}

func (m *Data) GetRawData() string {
	if m != nil {
		return m.RawData
	}
	return ""
}

func (m *Data) GetDataTiles() []*DataTile {
	if m != nil {
		return m.DataTiles
	}
	return nil
}

func (m *Data) GetChunks() []*Chunk {
	if m != nil {
		return m.Chunks
	}
	return nil
}

type DataTile struct {
	Gid                  uint32   `protobuf:"fixed32,1,opt,name=gid,proto3" json:"gid,omitempty"`
	X                    uint32   `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    uint32   `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataTile) Reset()         { *m = DataTile{} }
func (m *DataTile) String() string { return proto.CompactTextString(m) }
func (*DataTile) ProtoMessage()    {}
func (*DataTile) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{4}
}

func (m *DataTile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataTile.Unmarshal(m, b)
}
func (m *DataTile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataTile.Marshal(b, m, deterministic)
}
func (m *DataTile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataTile.Merge(m, src)
}
func (m *DataTile) XXX_Size() int {
	return xxx_messageInfo_DataTile.Size(m)
}
func (m *DataTile) XXX_DiscardUnknown() {
	xxx_messageInfo_DataTile.DiscardUnknown(m)
}

var xxx_messageInfo_DataTile proto.InternalMessageInfo

func (m *DataTile) GetGid() uint32 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *DataTile) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *DataTile) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Image struct {
	Source               string   `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Trans                string   `protobuf:"bytes,2,opt,name=trans,proto3" json:"trans,omitempty"`
	Width                int64    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int64    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Format               string   `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{5}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Image) GetTrans() string {
	if m != nil {
		return m.Trans
	}
	return ""
}

func (m *Image) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Image) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type Layer struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Opacity              float32     `protobuf:"fixed32,2,opt,name=opacity,proto3" json:"opacity,omitempty"`
	Visible              bool        `protobuf:"varint,3,opt,name=visible,proto3" json:"visible,omitempty"`
	Properties           []*Property `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty"`
	Data                 *Data       `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Tileset              *TileSet    `protobuf:"bytes,7,opt,name=tileset,proto3" json:"tileset,omitempty"`
	Empty                bool        `protobuf:"varint,8,opt,name=empty,proto3" json:"empty,omitempty"`
	Id                   int64       `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	X                    int64       `protobuf:"varint,10,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64       `protobuf:"varint,11,opt,name=y,proto3" json:"y,omitempty"`
	Height               int64       `protobuf:"varint,12,opt,name=height,proto3" json:"height,omitempty"`
	Width                int64       `protobuf:"varint,13,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Layer) Reset()         { *m = Layer{} }
func (m *Layer) String() string { return proto.CompactTextString(m) }
func (*Layer) ProtoMessage()    {}
func (*Layer) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{6}
}

func (m *Layer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Layer.Unmarshal(m, b)
}
func (m *Layer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Layer.Marshal(b, m, deterministic)
}
func (m *Layer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Layer.Merge(m, src)
}
func (m *Layer) XXX_Size() int {
	return xxx_messageInfo_Layer.Size(m)
}
func (m *Layer) XXX_DiscardUnknown() {
	xxx_messageInfo_Layer.DiscardUnknown(m)
}

var xxx_messageInfo_Layer proto.InternalMessageInfo

func (m *Layer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Layer) GetOpacity() float32 {
	if m != nil {
		return m.Opacity
	}
	return 0
}

func (m *Layer) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *Layer) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Layer) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Layer) GetTileset() *TileSet {
	if m != nil {
		return m.Tileset
	}
	return nil
}

func (m *Layer) GetEmpty() bool {
	if m != nil {
		return m.Empty
	}
	return false
}

func (m *Layer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Layer) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Layer) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Layer) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Layer) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

type Object struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string      `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	X                    float64     `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64     `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Width                float64     `protobuf:"fixed64,5,opt,name=width,proto3" json:"width,omitempty"`
	Height               float64     `protobuf:"fixed64,6,opt,name=height,proto3" json:"height,omitempty"`
	Gid                  int64       `protobuf:"varint,7,opt,name=gid,proto3" json:"gid,omitempty"`
	Visible              bool        `protobuf:"varint,8,opt,name=visible,proto3" json:"visible,omitempty"`
	Polygons             []*Polygon  `protobuf:"bytes,9,rep,name=polygons,proto3" json:"polygons,omitempty"`
	PolyLines            []*PolyLine `protobuf:"bytes,10,rep,name=poly_lines,json=polyLines,proto3" json:"poly_lines,omitempty"`
	Properties           []*Property `protobuf:"bytes,11,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{7}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Object) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Object) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Object) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Object) GetWidth() float64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Object) GetHeight() float64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Object) GetGid() int64 {
	if m != nil {
		return m.Gid
	}
	return 0
}

func (m *Object) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *Object) GetPolygons() []*Polygon {
	if m != nil {
		return m.Polygons
	}
	return nil
}

func (m *Object) GetPolyLines() []*PolyLine {
	if m != nil {
		return m.PolyLines
	}
	return nil
}

func (m *Object) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

type ObjectGroup struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color                string      `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Opacity              float32     `protobuf:"fixed32,3,opt,name=opacity,proto3" json:"opacity,omitempty"`
	Visible              bool        `protobuf:"varint,4,opt,name=visible,proto3" json:"visible,omitempty"`
	Properties           []*Property `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty"`
	Objects              []*Object   `protobuf:"bytes,6,rep,name=objects,proto3" json:"objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ObjectGroup) Reset()         { *m = ObjectGroup{} }
func (m *ObjectGroup) String() string { return proto.CompactTextString(m) }
func (*ObjectGroup) ProtoMessage()    {}
func (*ObjectGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{8}
}

func (m *ObjectGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectGroup.Unmarshal(m, b)
}
func (m *ObjectGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectGroup.Marshal(b, m, deterministic)
}
func (m *ObjectGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectGroup.Merge(m, src)
}
func (m *ObjectGroup) XXX_Size() int {
	return xxx_messageInfo_ObjectGroup.Size(m)
}
func (m *ObjectGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectGroup proto.InternalMessageInfo

func (m *ObjectGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ObjectGroup) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *ObjectGroup) GetOpacity() float32 {
	if m != nil {
		return m.Opacity
	}
	return 0
}

func (m *ObjectGroup) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

func (m *ObjectGroup) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ObjectGroup) GetObjects() []*Object {
	if m != nil {
		return m.Objects
	}
	return nil
}

type PolyLine struct {
	Points               string   `protobuf:"bytes,1,opt,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PolyLine) Reset()         { *m = PolyLine{} }
func (m *PolyLine) String() string { return proto.CompactTextString(m) }
func (*PolyLine) ProtoMessage()    {}
func (*PolyLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{9}
}

func (m *PolyLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolyLine.Unmarshal(m, b)
}
func (m *PolyLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolyLine.Marshal(b, m, deterministic)
}
func (m *PolyLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolyLine.Merge(m, src)
}
func (m *PolyLine) XXX_Size() int {
	return xxx_messageInfo_PolyLine.Size(m)
}
func (m *PolyLine) XXX_DiscardUnknown() {
	xxx_messageInfo_PolyLine.DiscardUnknown(m)
}

var xxx_messageInfo_PolyLine proto.InternalMessageInfo

func (m *PolyLine) GetPoints() string {
	if m != nil {
		return m.Points
	}
	return ""
}

type Polygon struct {
	Points               string   `protobuf:"bytes,1,opt,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Polygon) Reset()         { *m = Polygon{} }
func (m *Polygon) String() string { return proto.CompactTextString(m) }
func (*Polygon) ProtoMessage()    {}
func (*Polygon) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{10}
}

func (m *Polygon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Polygon.Unmarshal(m, b)
}
func (m *Polygon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Polygon.Marshal(b, m, deterministic)
}
func (m *Polygon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Polygon.Merge(m, src)
}
func (m *Polygon) XXX_Size() int {
	return xxx_messageInfo_Polygon.Size(m)
}
func (m *Polygon) XXX_DiscardUnknown() {
	xxx_messageInfo_Polygon.DiscardUnknown(m)
}

var xxx_messageInfo_Polygon proto.InternalMessageInfo

func (m *Polygon) GetPoints() string {
	if m != nil {
		return m.Points
	}
	return ""
}

type Property struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Property) Reset()         { *m = Property{} }
func (m *Property) String() string { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()    {}
func (*Property) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{11}
}

func (m *Property) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Property.Unmarshal(m, b)
}
func (m *Property) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Property.Marshal(b, m, deterministic)
}
func (m *Property) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Property.Merge(m, src)
}
func (m *Property) XXX_Size() int {
	return xxx_messageInfo_Property.Size(m)
}
func (m *Property) XXX_DiscardUnknown() {
	xxx_messageInfo_Property.DiscardUnknown(m)
}

var xxx_messageInfo_Property proto.InternalMessageInfo

func (m *Property) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Property) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Property) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type ImageLayer struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OffsetX              int64    `protobuf:"varint,3,opt,name=offset_x,json=offsetX,proto3" json:"offset_x,omitempty"`
	OffsetY              int64    `protobuf:"varint,4,opt,name=offset_y,json=offsetY,proto3" json:"offset_y,omitempty"`
	X                    int64    `protobuf:"varint,5,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,6,opt,name=y,proto3" json:"y,omitempty"`
	Opacity              float32  `protobuf:"fixed32,7,opt,name=opacity,proto3" json:"opacity,omitempty"`
	Visible              bool     `protobuf:"varint,8,opt,name=visible,proto3" json:"visible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageLayer) Reset()         { *m = ImageLayer{} }
func (m *ImageLayer) String() string { return proto.CompactTextString(m) }
func (*ImageLayer) ProtoMessage()    {}
func (*ImageLayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{12}
}

func (m *ImageLayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageLayer.Unmarshal(m, b)
}
func (m *ImageLayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageLayer.Marshal(b, m, deterministic)
}
func (m *ImageLayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageLayer.Merge(m, src)
}
func (m *ImageLayer) XXX_Size() int {
	return xxx_messageInfo_ImageLayer.Size(m)
}
func (m *ImageLayer) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageLayer.DiscardUnknown(m)
}

var xxx_messageInfo_ImageLayer proto.InternalMessageInfo

func (m *ImageLayer) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ImageLayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImageLayer) GetOffsetX() int64 {
	if m != nil {
		return m.OffsetX
	}
	return 0
}

func (m *ImageLayer) GetOffsetY() int64 {
	if m != nil {
		return m.OffsetY
	}
	return 0
}

func (m *ImageLayer) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ImageLayer) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *ImageLayer) GetOpacity() float32 {
	if m != nil {
		return m.Opacity
	}
	return 0
}

func (m *ImageLayer) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

type Group struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OffsetX              int64    `protobuf:"varint,3,opt,name=offset_x,json=offsetX,proto3" json:"offset_x,omitempty"`
	OffsetY              int64    `protobuf:"varint,4,opt,name=offset_y,json=offsetY,proto3" json:"offset_y,omitempty"`
	Opacity              float32  `protobuf:"fixed32,7,opt,name=opacity,proto3" json:"opacity,omitempty"`
	Visible              bool     `protobuf:"varint,8,opt,name=visible,proto3" json:"visible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{13}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetOffsetX() int64 {
	if m != nil {
		return m.OffsetX
	}
	return 0
}

func (m *Group) GetOffsetY() int64 {
	if m != nil {
		return m.OffsetY
	}
	return 0
}

func (m *Group) GetOpacity() float32 {
	if m != nil {
		return m.Opacity
	}
	return 0
}

func (m *Group) GetVisible() bool {
	if m != nil {
		return m.Visible
	}
	return false
}

type Chunk struct {
	X                    int64    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width                int64    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int64    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e07cbeaab58e6ef, []int{14}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Chunk) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Chunk) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Chunk) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Map)(nil), "pb.Map")
	proto.RegisterType((*Tile)(nil), "pb.Tile")
	proto.RegisterType((*TileSet)(nil), "pb.TileSet")
	proto.RegisterType((*Data)(nil), "pb.Data")
	proto.RegisterType((*DataTile)(nil), "pb.DataTile")
	proto.RegisterType((*Image)(nil), "pb.Image")
	proto.RegisterType((*Layer)(nil), "pb.Layer")
	proto.RegisterType((*Object)(nil), "pb.Object")
	proto.RegisterType((*ObjectGroup)(nil), "pb.ObjectGroup")
	proto.RegisterType((*PolyLine)(nil), "pb.PolyLine")
	proto.RegisterType((*Polygon)(nil), "pb.Polygon")
	proto.RegisterType((*Property)(nil), "pb.Property")
	proto.RegisterType((*ImageLayer)(nil), "pb.ImageLayer")
	proto.RegisterType((*Group)(nil), "pb.Group")
	proto.RegisterType((*Chunk)(nil), "pb.Chunk")
}

func init() { proto.RegisterFile("pb/tmx.proto", fileDescriptor_9e07cbeaab58e6ef) }

var fileDescriptor_9e07cbeaab58e6ef = []byte{
	// 1195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4b, 0x8f, 0xdb, 0x36,
	0x17, 0x85, 0x6c, 0xcb, 0x92, 0xae, 0xed, 0x99, 0x7c, 0xfc, 0xa6, 0x81, 0x92, 0x3e, 0x32, 0xa3,
	0xa6, 0xed, 0xf4, 0x81, 0x29, 0xfa, 0x58, 0x74, 0x5b, 0x4c, 0x81, 0x64, 0x80, 0x29, 0x92, 0x2a,
	0x45, 0x1f, 0x2b, 0x41, 0xb6, 0x68, 0x9b, 0x8d, 0x2c, 0x0a, 0x24, 0x9d, 0xb1, 0xd0, 0x7d, 0xff,
	0x41, 0xff, 0x44, 0x37, 0x05, 0x8a, 0xa2, 0xdb, 0xfe, 0xb5, 0x82, 0x97, 0xa4, 0x2c, 0xcf, 0x23,
	0x83, 0x14, 0xe8, 0x8e, 0xf7, 0xdc, 0x2b, 0x91, 0x3c, 0xe7, 0xdc, 0x2b, 0xc1, 0xb8, 0x9e, 0x7e,
	0xac, 0x56, 0x9b, 0x93, 0x5a, 0x70, 0xc5, 0x49, 0xaf, 0x9e, 0xde, 0xd7, 0x08, 0x5f, 0x2b, 0x83,
	0x24, 0xbf, 0x0c, 0xa1, 0xff, 0x75, 0x5e, 0x93, 0x18, 0x82, 0x17, 0x54, 0x48, 0xc6, 0xab, 0xd8,
	0x3b, 0xf4, 0x8e, 0xa3, 0xd4, 0x85, 0xe4, 0x10, 0x46, 0x5c, 0x30, 0x5a, 0xa9, 0x5c, 0xe9, 0x6c,
	0x0f, 0xb3, 0x5d, 0x88, 0x1c, 0x80, 0x7f, 0xc1, 0x0a, 0xb5, 0x8c, 0xfb, 0x87, 0xde, 0x71, 0x3f,
	0x35, 0x01, 0xb9, 0x0b, 0xc3, 0x25, 0x65, 0x8b, 0xa5, 0x8a, 0x07, 0x08, 0xdb, 0x88, 0xbc, 0x09,
	0xa0, 0x58, 0x49, 0x33, 0xf3, 0x88, 0x8f, 0xb9, 0x48, 0x23, 0xdf, 0xe3, 0x63, 0x0f, 0x60, 0x84,
	0x69, 0xfb, 0xec, 0x10, 0xf3, 0xf8, 0xc4, 0x63, 0xf3, 0xfc, 0x47, 0x00, 0xb5, 0xe0, 0x35, 0x15,
	0x8a, 0x51, 0x19, 0x07, 0x87, 0xfd, 0xe3, 0xd1, 0xa7, 0xe3, 0x93, 0x7a, 0x7a, 0xf2, 0xd4, 0xa0,
	0x4d, 0xda, 0xc9, 0x93, 0x23, 0x18, 0x96, 0x79, 0x43, 0x85, 0x8c, 0x43, 0xac, 0x8c, 0x74, 0xe5,
	0xb9, 0x46, 0x52, 0x9b, 0x20, 0x9f, 0xc3, 0x84, 0x4f, 0x7f, 0xa2, 0x33, 0x95, 0x2d, 0x04, 0x5f,
	0xd7, 0x32, 0x8e, 0xb0, 0x72, 0x5f, 0x57, 0x3e, 0xc1, 0xc4, 0x23, 0x8d, 0xa7, 0x63, 0xbe, 0x0d,
	0x24, 0x79, 0x1b, 0x26, 0xfa, 0x50, 0x45, 0xe6, 0x68, 0x03, 0x24, 0x66, 0x8c, 0xe0, 0x77, 0x96,
	0xbb, 0x23, 0x18, 0x0b, 0x5a, 0x15, 0x54, 0x64, 0x5c, 0x14, 0x54, 0xc4, 0x23, 0x43, 0x9e, 0xc1,
	0x9e, 0x68, 0x88, 0xdc, 0x87, 0x90, 0x55, 0x73, 0x56, 0x31, 0x45, 0xe3, 0x31, 0x5e, 0xb6, 0x8d,
	0xc9, 0xbb, 0xb0, 0xbf, 0xa4, 0x9b, 0x4c, 0xb2, 0x82, 0x66, 0x25, 0xad, 0x16, 0x6a, 0x19, 0x4f,
	0xb0, 0x64, 0xb2, 0xa4, 0x9b, 0x67, 0xac, 0xa0, 0xe7, 0x08, 0xea, 0x6d, 0xa4, 0xca, 0x17, 0x0b,
	0x2a, 0xb2, 0x7c, 0xc3, 0x64, 0xbc, 0x67, 0xb6, 0xb1, 0xd8, 0x97, 0x1b, 0x26, 0xc9, 0xfb, 0x70,
	0x67, 0x9a, 0xcf, 0x9e, 0xeb, 0x1b, 0x56, 0x45, 0x36, 0xe3, 0x25, 0x17, 0xf1, 0x3e, 0x96, 0xed,
	0x6f, 0xf1, 0x53, 0x0d, 0x93, 0x04, 0x26, 0x15, 0xdd, 0xa8, 0x0c, 0xe9, 0xc9, 0x58, 0x11, 0xdf,
	0x31, 0xaf, 0xd3, 0x20, 0x32, 0x77, 0x56, 0x90, 0x87, 0xb0, 0x87, 0x35, 0x96, 0x38, 0x56, 0xc4,
	0xff, 0x33, 0xd7, 0xd7, 0xa8, 0x21, 0xed, 0xac, 0x20, 0xc7, 0x80, 0xc2, 0x66, 0x92, 0x2a, 0x19,
	0x13, 0x64, 0x75, 0xa4, 0x59, 0xfd, 0x96, 0x95, 0xf4, 0x19, 0x55, 0x69, 0xa8, 0xcc, 0x42, 0x92,
	0x4f, 0x60, 0xcc, 0x56, 0xf9, 0x82, 0x66, 0x56, 0xac, 0xff, 0x63, 0xf1, 0x9e, 0x2e, 0x3e, 0xd3,
	0xb8, 0x51, 0x6c, 0xc4, 0xda, 0x35, 0x2a, 0x6b, 0xf5, 0x3a, 0xd8, 0x2a, 0x6b, 0x94, 0xb2, 0x09,
	0xf2, 0x01, 0x44, 0x33, 0x5e, 0x96, 0xac, 0xd0, 0xaf, 0x7c, 0x6d, 0xeb, 0x94, 0x53, 0x0b, 0xa6,
	0xdb, 0x74, 0x32, 0x87, 0x81, 0x3e, 0x16, 0xd9, 0x83, 0x1e, 0x2b, 0xb0, 0x07, 0xfa, 0x69, 0x8f,
	0x15, 0x84, 0xc0, 0x40, 0x35, 0x35, 0xb5, 0xbe, 0xc7, 0xb5, 0x6e, 0x16, 0x45, 0x85, 0xc8, 0x59,
	0x85, 0x96, 0x8f, 0x52, 0x17, 0xea, 0x66, 0xa9, 0x05, 0x9f, 0xe6, 0x53, 0x56, 0x32, 0xd5, 0xa0,
	0xf3, 0x7b, 0x69, 0x17, 0x4a, 0xfe, 0xec, 0x43, 0x60, 0xef, 0x4f, 0x5e, 0x87, 0x68, 0xce, 0x84,
	0x54, 0xd9, 0xa2, 0xdd, 0x32, 0x44, 0xe0, 0x11, 0x2b, 0x74, 0xff, 0x48, 0xbe, 0x16, 0x33, 0xb7,
	0xb5, 0x8d, 0xf4, 0x81, 0xaa, 0x7c, 0x45, 0xed, 0xce, 0xb8, 0xbe, 0xd4, 0x53, 0x83, 0x5b, 0x7a,
	0xca, 0xbf, 0xd2, 0x53, 0x31, 0x04, 0xb2, 0xce, 0x67, 0xac, 0x5a, 0xd8, 0x86, 0x73, 0xa1, 0x3e,
	0xc5, 0x2a, 0x17, 0x0b, 0x56, 0xc5, 0x81, 0xe9, 0x62, 0x13, 0x5d, 0xea, 0xc2, 0xf0, 0x96, 0x2e,
	0x7c, 0x00, 0x3e, 0x4a, 0x17, 0x47, 0x87, 0x9e, 0x93, 0x0a, 0x75, 0x4d, 0x0d, 0x4e, 0xde, 0x02,
	0x5f, 0x1f, 0x47, 0xc6, 0x80, 0x6f, 0x0a, 0x9d, 0x4b, 0x52, 0x03, 0xb7, 0x17, 0x9c, 0xf1, 0x75,
	0xa5, 0xb0, 0x8d, 0xec, 0x05, 0x4f, 0x35, 0xa0, 0x1b, 0x60, 0xc6, 0xcb, 0xf5, 0xaa, 0xb2, 0x05,
	0xa6, 0x91, 0x46, 0x06, 0x33, 0x25, 0x9d, 0x01, 0x37, 0xd9, 0x1d, 0x70, 0x57, 0x3a, 0x79, 0xef,
	0x6a, 0x27, 0x27, 0xbf, 0x7b, 0x30, 0xf8, 0x2a, 0x57, 0xb9, 0xee, 0x57, 0x5a, 0xcd, 0x78, 0xa1,
	0xb9, 0x32, 0x93, 0xb2, 0x8d, 0xb5, 0xfa, 0x33, 0xbe, 0xaa, 0x05, 0x95, 0xb2, 0x33, 0x2a, 0x3b,
	0x10, 0xb9, 0x07, 0xa1, 0xc8, 0x2f, 0xb2, 0x22, 0x57, 0xb9, 0xb3, 0x8e, 0xc8, 0x2f, 0xf0, 0xc5,
	0x1f, 0x02, 0x68, 0x38, 0x33, 0x3c, 0x0c, 0xb6, 0x8c, 0xea, 0x2c, 0x72, 0x11, 0x15, 0x76, 0x85,
	0xe6, 0x9f, 0x2d, 0xd7, 0xd5, 0x73, 0x19, 0xfb, 0x5b, 0xf3, 0x9f, 0x6a, 0x24, 0xb5, 0x89, 0xe4,
	0x0b, 0x08, 0xdd, 0x93, 0xe4, 0x0e, 0xf4, 0x9d, 0xc5, 0x82, 0x54, 0x2f, 0xc9, 0x18, 0xbc, 0x0d,
	0x1e, 0x30, 0x48, 0xbd, 0x8d, 0x8e, 0x1a, 0x3c, 0x4f, 0x90, 0x7a, 0x4d, 0xf2, 0x33, 0xf8, 0x28,
	0x4e, 0xc7, 0x82, 0xde, 0x8e, 0x05, 0x0f, 0xc0, 0x57, 0x22, 0xaf, 0xa4, 0xbd, 0xa1, 0x09, 0x5e,
	0xf1, 0x33, 0x70, 0x17, 0x86, 0x73, 0x2e, 0x56, 0xb9, 0xb1, 0x63, 0x94, 0xda, 0x28, 0xf9, 0xa3,
	0x07, 0x3e, 0x76, 0x78, 0x6b, 0x74, 0xaf, 0x63, 0xf4, 0x18, 0x02, 0xae, 0x9d, 0xa9, 0x1a, 0xdc,
	0xbb, 0x97, 0xba, 0x10, 0xf5, 0x65, 0x92, 0x4d, 0x4b, 0xd3, 0x19, 0x61, 0xea, 0xc2, 0x4b, 0x56,
	0x1d, 0xdc, 0x62, 0xd5, 0x37, 0x60, 0x80, 0xea, 0xf8, 0xe8, 0xd4, 0xd0, 0x09, 0x90, 0x22, 0x4a,
	0xde, 0x81, 0x00, 0xf5, 0xa1, 0x0a, 0xfb, 0xe1, 0xd2, 0x3c, 0x73, 0x39, 0x4d, 0x05, 0x5d, 0xd5,
	0xaa, 0x89, 0x43, 0x3c, 0x8a, 0x09, 0xec, 0x68, 0x89, 0xda, 0xd1, 0x82, 0x1a, 0x00, 0x86, 0x4e,
	0x03, 0xe3, 0x6c, 0xaf, 0xe9, 0xd0, 0x36, 0xde, 0xa1, 0xad, 0x25, 0x79, 0xd2, 0x21, 0x39, 0xf9,
	0xad, 0x07, 0x43, 0x33, 0x75, 0xaf, 0x65, 0xed, 0xba, 0x19, 0x86, 0x9b, 0x6b, 0xa6, 0xbc, 0x76,
	0xf3, 0x81, 0x89, 0x9a, 0xed, 0x26, 0x3e, 0x22, 0x57, 0x94, 0x1c, 0x22, 0xec, 0x8e, 0x64, 0xcd,
	0x65, 0xe6, 0x03, 0x9a, 0xab, 0xa3, 0x45, 0xb8, 0xab, 0xc5, 0x7b, 0x10, 0xd6, 0xbc, 0x6c, 0x16,
	0xbc, 0x72, 0x9f, 0x59, 0x24, 0xf0, 0xa9, 0xc1, 0xd2, 0x36, 0xa9, 0xbb, 0x41, 0xaf, 0xb3, 0x92,
	0x55, 0xed, 0x54, 0x18, 0xbb, 0xd2, 0x73, 0x56, 0xd1, 0x34, 0xaa, 0xed, 0x4a, 0x5e, 0x52, 0x78,
	0xf4, 0x72, 0x85, 0x93, 0xbf, 0x3d, 0x18, 0x75, 0xbe, 0xeb, 0xd7, 0x32, 0x76, 0x00, 0xbe, 0xf9,
	0x46, 0x5a, 0x87, 0x63, 0xd0, 0x75, 0x5f, 0xff, 0x46, 0xf7, 0x0d, 0x5e, 0xe6, 0x3e, 0xff, 0x16,
	0xf7, 0x3d, 0x84, 0xc0, 0x7c, 0x52, 0x65, 0x3c, 0xc4, 0x52, 0xd8, 0xfe, 0x85, 0xa4, 0x2e, 0x95,
	0x24, 0x10, 0x3a, 0x1a, 0xb4, 0x2a, 0x35, 0x67, 0x95, 0x92, 0xae, 0x47, 0x4d, 0x94, 0x1c, 0x41,
	0x60, 0x59, 0xbd, 0xb1, 0xe4, 0x31, 0x84, 0xee, 0x10, 0x37, 0x91, 0xf0, 0x22, 0x2f, 0xd7, 0xce,
	0x37, 0x26, 0x68, 0xcd, 0xd4, 0xdf, 0x9a, 0x29, 0xf9, 0xcb, 0x03, 0xd8, 0x7e, 0xa7, 0xaf, 0xfb,
	0x86, 0xe2, 0xcb, 0x7b, 0x9d, 0x97, 0xdf, 0x83, 0x90, 0xcf, 0xe7, 0x92, 0xaa, 0x6c, 0x63, 0x07,
	0x46, 0x60, 0xe2, 0x1f, 0x3a, 0xa9, 0xc6, 0x0e, 0x0d, 0x9b, 0xfa, 0xd1, 0xb8, 0xd6, 0xdf, 0x69,
	0x99, 0xa1, 0x6b, 0x99, 0x8e, 0x3a, 0xc1, 0x8d, 0xea, 0xec, 0xfa, 0x31, 0xf9, 0xd5, 0x03, 0xdf,
	0xb8, 0xe0, 0xbf, 0x3b, 0xf3, 0xbf, 0x39, 0xd7, 0x37, 0xe0, 0xe3, 0x34, 0x37, 0x17, 0xf6, 0x76,
	0x2e, 0xdc, 0x73, 0x17, 0x7e, 0xa5, 0x81, 0x3b, 0x1d, 0xe2, 0x0f, 0xff, 0x67, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xe8, 0xf3, 0xda, 0x2a, 0x12, 0x0c, 0x00, 0x00,
}
